title: Old Programmer, New Programs
author: Billy Murphy
email: billymur@swbell.net
description: This site will document the journey of an old programmer learning the new ways of programming.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
